#!/bin/sh

#
# Precommit message validation to conform to the standard 'Title (opt): message'
# specification.
#
# Copy this file to your local repository:
#   cp commit-msg .git/hooks/
#
# Foo: bar roo
# Foo (bar): roo
# 24: foo bar
# 25 (foo): bar roo
# Foo: 26 bar roo
#

commit_msg=$(grep -v '^#\|^$' "$1")

if echo "$commit_msg" | egrep '^[A-Z0-9].*:\s.+' > /dev/null; then
    exit 0
else
    echo >&2 "hooks/commit-msg: not conforming to 'Title (opt)?: message' spec; aborted"
    exit 1
fi
