#!/bin/sh

if [ ! $(which riverctl &> /dev/null) ]; then
    alias riverctl="$HOME/.local/bin/riverctl"
    alias rivertile="$HOME/.local/bin/rivertile"
fi

TERMINAL=${TERMINAL:-foot} # fallback

if [ "$INIT_TERMINAL" -eq 1 ]; then
    riverctl spawn "$TERMINAL"
fi

# fork
riverctl map normal Super Return spawn "$TERMINAL"
riverctl map normal Super Q close
riverctl map normal Super+Shift E exit

# windows
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super Space zoom
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# move windows
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100
riverctl map-pointer normal Super BTN_LEFT move-view

# snap windows
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right
riverctl map normal Super F toggle-float
riverctl map normal Super G toggle-fullscreen

# resize windows
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100
riverctl map-pointer normal Super BTN_RIGHT resize-view

# tags
for i in $(seq 1 9); do
    tags=$((1 << ($i - 1)))
    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags
done

# display
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# tile manager (DWM style)
riverctl default-layout rivertile
rivertile -main-ratio 0.5 -view-padding 3 -outer-padding 5 &
